export { default as Header } from './header/Header'
export { default as HeroSection } from './heroSection/HeroSection'
export { default as AboutMe } from './aboutMe/AboutMe'
export { default as MyServices } from './myServices/MyServices'
export { default as CardComponent } from './cardComponent/CardComponent'
export { default as IconsDiv } from './iconsDiv/IconsDiv'
